defaults:
 - model: funnel.yaml
 - sampler: hmc.yaml
 - _self_

repeats: 5
rng_key: 1
hydra:
  run:
    dir: logs/model=${model.model_name}/dim=${model.dim}{model.sub_subname}/${hydra.job.override_dirname}/rng_key=${rng_key}
  sweep:
    dir: logs/model=${model.model_name}/dim=${model.dim}{model.sub_subname}/${hydra.job.override_dirname}
    subdir: rng_key=${rng_key}
  job:
    config:
      override_dirname:
        exclude_keys:
          - rng_key
          - model
